version: "3"
services:
  graphql:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - .:/home/node/app
    ports:
      - 4000:4000
    networks:
      - backend
    depends_on:
      - db
    command: npm run dev
  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=root
    networks:
      - backend
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
networks:
  backend: